apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: keeper
  namespace: clickhouse
spec:
  replicas: 3
  containerTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    storageClassName: gp3
    resources:
      requests:
        storage: 10Gi
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  replicas: 2
  shards: 1
  keeperClusterRef:
    name: keeper
  containerTemplate:
    resources:
      requests:
        cpu: "2"
        memory: 8Gi
      limits:
        cpu: "2"
        memory: 8Gi
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    storageClassName: gp3
    resources:
      requests:
        storage: 10Gi
