---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pull
  namespace: market-maker
spec:
  encryptedData:
    .dockerconfigjson: AgAiVqYW0yytRd55FNGeKEscoo7gYnZosN/6JYuQikyHm4+p6o5v4q8vWNueERgP7lpa2y/G6CU8sKkWlDFXHAC6qa9rEvvnBbz97iy0GTsh5ARs4wqWaaXBURYJHbxJEa3EiOg2uS8wVMkYZagbXm4LRs+WCtGJOBlydhNHX+HRU9GvX7ce5dfe8CGNDlrLGD/m6bgHaALgZANJQFvO611Uvoo5h3Ijn9HNSIoGmIJmpZWqnzJ5LCal8Wm/rKcEpwOdtIcouYGxP3MDtPK14mjgopIA/yEiGtjKmbGES7WbOo2YUFGu9oIwLP4SlziwLjAISBPVdPhhfqdkoxD5A35nwidoA/CMwpO2/KjT5zi/qerEiT7KnJysNcW0PsjzhG/sfZc0w3E9Ml1/ZjIiU+wfGLumiZQrh6T3xidrlDcfRG9ULE5dN7Ax89vSDch28Xm+xl0FUp1DAyBqCarwu7QZo4ZRx9AjXiw5zjUwV5CdwjsSwI5HAUzJ8CwFJsTvKQdksCCh6dswx7zTZvHlk0dtnOkx0xlLxQeUrzGT4QNCvD5bq/SEVlcqYhbekP14rSwE4RlR34SJBOlD9dQIX7LUtk2E03dek4SL+QQ45t6Faan7JA8yVkhVObHs4Vq2hUEFgzv5eIjGIJ6nUg3swubcQZ7uilG9v3C0zqurJWmgR5alBLUEGSDMiydSxwgTjklVOOXcgyXtmKJz5bxs5WUWhCKerGpN+LJcdCpn94DYZ7b3O4HSpnaCxOCzDnkbXPzoD8/2Bn26fWeYshsZmHb3WMQVlZ82qsQq72ucnNjkoWqEwhHPaErb9IKMKmd7XMnFyFaTsYcFqIvfDxuwa4JzpEwTGSVNLndyruf9Sf21Pmekx0qGdZi5hcsWXADnsO9rrd/YYtSmNhNxGaw9arS2uhpVTdL+2C4S7T/n39MHmIRKPj+C4LD/VV0OU5qPEg==
  template:
    metadata:
      name: dockerhub-pull
      namespace: market-maker
    type: kubernetes.io/dockerconfigjson
