---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pull
  namespace: prediction-maker
spec:
  encryptedData:
    .dockerconfigjson: AgAF3TBogW27lNSy5FvJG502Ep8MQcRh0OAwH5YAl/EKTd9lQVG+mh1Zcr6W19MH0d9oFQteeIe06j+3cDSZZKrr1fACo7Hvp7naQHyhjj4kpzgIod8IR+/9tcF0GXlA9M4R/mYMLbfD+P5hQVrTBYrpQNGdqBspCz4IZYfJ1RE9t4RYCFVdsv7XhefN8834ELQY0jEf17FezKgS95JYdep9BZtrhCU0nJnmbUIgYYoH6K0J7hjRWW4EbDDbbKQVvPdQLnZdbGwkT8ovCYsIuZiwClUoXigaRnTL7ytyLKEsRPGb5NSlXk3j286GLtQiS4FUNUkojCUOU9kZjNtOZsMrJ4cyUbO6/gtTphDAt3Jsu2BDGN+CMcRfMgLdcihv5UWBv0/d3k8eEQ/SkwfGbfyiPDaoKZC+C8imcf2U8o/zdVFMOWx2zKkPMswxRG0Acy2dvWQLOxLisLzWNsQsR6zTr4DhZXGoY7GFGuJRrWaTQGJ30XnfO5o0lObLqQc54ThDaE1OOrzIx1HgShyAr9nuy5fxHgrDVDv6Dz7P0xgwpSOg1KpnchVDW50VRQQ1aBVZJrFwHJbXdsnNgS16ljz1PLQeTpwPuqU1zwRxu47LBa/w4rxyygEL2hXqwbSTGLkKazNcEXmuy3vZJGIR2/QBDPv4ENWeF+Bxc12gJrXNgCiLgAP1x0soQ3AyBwnR8mvNG5m0Od0OZokZo5LSqrQXkgTz9YUNn+E5dA5ev8coBVFRnBwz/flnc3Cph4nRFPyu3Uzg56u2JjCpcEJJWhe+9Ou+bZEh8sDDJd1AWlSEuwdCZ6a0V/7XbyCCTyjHDr/mLxRBm8KtUJVrsNvPgQ9w86u0sh2wBNR7SQzEEZHjGpSJYo+Aqp28gZQ1gOqe7++4H/rd2SbwXXMZVi+AidPsuYyihY3TYzkCQ33x608F9z2fV7qcYufnlVJAWmdFdw==
  template:
    metadata:
      name: dockerhub-pull
      namespace: prediction-maker
    type: kubernetes.io/dockerconfigjson
