---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pull
  namespace: user-bot
spec:
  encryptedData:
    .dockerconfigjson: AgB6ZN2ICLo65sNrtO165DWzhKa5CeYlgCttdbpR8RI/DuxQKpe83pJ+UCQO1rQmQHAYkydk7DY/9X25SVPsDUjmbtLNrsDXzOnzxaJniUWSoyA0KNeD+xeuw7WpFSGZwfjQzXcs59zA1zM0FTNDnZf+E0QghKc2hzHqH8afAb3zIysm1PXLXELv328v6nfvANPciPhpjxGsxRZ7zDkkPyx/fr4MMP+3p9jaZ/XPU1rtIxSHwL35dGM4afFDtyR4skuphPX4muFAU4d4dVAs8InsviuPlHFbIr073lj6Ad2D/FQcXnYXMUk7+4fPBCb4sEIvOK0Aat9vI+XWxsvk7dwEfQbzaoAzkmY2+V4ranmQl3yAeJUsg5aNpiDckIt3Jz/Ty/O4K9p7aSJ7+Yoc2eLAXeaQAlUCAscydwmy3QU6G3zlneLZVtTel2Famqs73bkUStb9qEIYKQKIEK5grRk2PcReuKgfBdMuIq3yVlkiQFNf+Mi+VmBYc4JWYyp3C5K/XeDwo4b3/5+VdYCq3q5YbsRWvHeRouZ4ULlqNMYVj1M7p88r+Ri0xSQE0wutxWNucGLqxxVySenN6sXt6vyl0P+VXAHyWmzIwlSY7K0cL9vBW8LwN1h+K2RTXWbJ8z3YS+gdnWvVeEgSg81Hb94YyQ8dkE2Cga/HOjHJIixFQOwNM9pg5s+t5JerVcG5VWeAWwnFKCl8vNMBd4Ebgaa5Zp7ixTRSR8vzx8Sa28z0PDwidMcUVEyCCD6HvWC6ecJoBeQE73TsF47ol320aalMdI5JHUpYQDQgIzolazBEyk/MNboWjI5VcnC5yMRKP2DfclT50tu2K2B+d6rBScaGT1y1X+5sxSQKaeZ8O3fhVUktmw0SSBhVx3HyPC6zNPY43oK7OW4C/jZqvsJF9iFqD4sW5pSMgXkW0Th2aGE5uPwmGvLrf/ZX1jYk1/68HQ==
  template:
    metadata:
      name: dockerhub-pull
      namespace: user-bot
    type: kubernetes.io/dockerconfigjson
