apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: user-bot
resources:
- namespace.yml
- service-account.yml
- common-env.yml
- sealed-secret.yml
- dockerhub-pull.sealed-secret.yml
- deployment.yml
- pvc.yml
configMapGenerator:
- files:
  - user-flow.toml
  name: user-bot-config
images:
- name: docker.io/labseterna/if-market-beta-user-bot
  newName: docker.io/labseterna/if-market-beta-user-bot
  newTag: sha-de35523
