apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-bot-runtime
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
