---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pull
  namespace: postgres-worker
spec:
  encryptedData:
    .dockerconfigjson: AgBkzbF/nQvM+UJERY/A38hrWpjIBVQGtJNY6/ElfTIht3nznPHh7eh8yYZudabNqaNDgOR/rTlHjiw7+leZYZnnSbvik4NO8nHV1H2V9O+MDphPPYgp0LZjRRA64IlraUQGtQ/6gBDe7PS6Vt0Mu9bFg4xeFmIhUuNQhDuMNkPaMd2/dpxbyVw5QirUyz1qW/qAjMJh68wVLpFdty1Y0DJedak5Ov3dWQxKAqJBv71Kp34dSOwlluEBIyv3medUroVPwtJyiMw3v9McP9vIotQuGAKPMoVg6mgb82Sn3/ZyBLntLDmfUa9zCoV45fmPk0D7Oi14zKGA8u13vhkXmIbC1xffop4hkss2FxtmkzG4E0eBOtgTp185DSpjjjGQN7W4WKzxu2RU2rWGBbG5ble0OGiKwXOgY/qELIPZ69to2w33Zr5+pAmb3okIiPETo3bUSnHzcJwqOBP9LgPciYxB7fvouRUOGqOkrpp03fplxdDWh9OwU71RKar6W0ej5m+Pcz4/qtZkgXLM7UEZrA3vGw3B3p5IfSvhX5TR03KoPwAREIj2Qoj5/3FqQTOy3ENY68NWKFInysQmvxLMy/15f2mfZjXFxKr46Heb8DwGP24ZNUxVorl783QslHG2ru0y8tDtiLWYziRrKrZzeHKzatsfgO+v/rXh4Rpl/Yzill+yLDfbEZHF0iYymBYghmzEPjTg4Soa8NRTwRTBsMaUMFzuX6yFY6daLlDWIOzMjYPvPtMlZf2dV4nlpetfuFLkBKdexE+xwpOMTvPDaK0rgE3RNhUdjeLT6eZnhfca5Qh+W9lDONGCq4gYQW5Jp3cjhrIO7YGACJnzYPDfj5xAFBskApUQ957sLBlRc67MmTau6kpdnZ2ut/pas911KOhwd/GT4UmUD2tJJtkwduCqTDKYYjY/LW+7kU+2L2qYj0+16y8GqVAFNr9Jrm3EbQ==
  template:
    metadata:
      name: dockerhub-pull
      namespace: postgres-worker
    type: kubernetes.io/dockerconfigjson
