apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: beta-if-market
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/eternalabs/if-market-ops.git
        revision: main
        directories:
          - path: "*"
          - path: argocd
            exclude: true
          - path: walkthrough
            exclude: true
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/eternalabs/if-market-ops.git
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
