---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pull
  namespace: s3-worker
spec:
  encryptedData:
    .dockerconfigjson: AgB+mY+sKa19nChjUW9Inz8NfNnZY2k2avumphRcTR9/A8NExyvcj56twiK293BKiv+7nV8E3oYh5nTrcnC2sh2S50DqEmYmdMDIqIWKIUb3aY8/YiEbcagKlY6zcqqNsDdefN1cle1iaUGHOGN4O+89D4EmGXF0LMPY1yDrQ54YbQ9396xreF6nxau1Wz0nRJOB5stbE4fq9ElfBn7lldgt1NQkAlU/yTw5RL7FWOoE1gzJCeJZye9eST6CygB+uKz/txg3JSKem+bBVXTgaMxOTkYz3iFzVyeUMz8e2aLnRNS4KXHALhMzr+M36wwlmgMkYo/OB5zKmP0GfT9yiMuyU4aJFBPsGz2xC0RYKcZMcCMFHOAMoum9nqYmnS3j0ecCZkXN3bq4hXqUJNPhHL+zuZwwykNrPDveYO1zEtSwe4RbUpC5w21pdOAt4GqFXNxNzQd5d6bbX/rcYZ8QFrVcUE7RmRpKUtzeGrt/zUANnqstnhPwRO7NHJHKm/QwtDPX+QYbfrZ0GmbXhUZj0rmDE2OBIqIE6idx55eQOIrmfu6HVpasZ4VFF6fC/j7rZP9KWbGAEyTLsa5ftIEmQaztW6WVCn+aI+n/gAAqahYCghP3a5A/gWfOAeiPBY+yvk2ZipTprbsyjosbTinsypMlbmgXAafpkJQLgcmG9Gi37Pn7Sk2Cavmc010jcHV0514bhBkHvS0hA4c6ObcBglv3Ld583f4mAEVvfHdfCiderOIKdda7J8YJpNGuOXZeCrAvz1blTlv9v8Vdms7DuqRdAg1XDAVHLYcgw6AioHGZhVwzO/gAfJy4XB4AdhePmBgvnwmoJZ23iDHv34st9N0UCKMSAysDFv+redm8KabEYLUVwopSKrO2lY7qyC+vpNlKn1tWWyXF/vPwRFy2/Dwr9P12O5q2JQbWsQnFQCZpw1bbyYSRcM4XQ8krjNY7Jg==
  template:
    metadata:
      name: dockerhub-pull
      namespace: s3-worker
    type: kubernetes.io/dockerconfigjson
