---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-worker-secrets
  namespace: s3-worker
spec:
  encryptedData:
    S3_WORKER_KAFKA_BROKERS: AgCxuN2YjIdMV8vm0VxJqzSGwNPTjeJ7EvAMiF818Tuim28JDOFTe5wFeD4Wr5rkQFi1N+xJMc3b6opBQLCe/7vKZob3ImYRJvRUIBjORJ0mZGqp66DnrZ/hLh1r33J0K35vLVnOwlAyE14laVcQIMbwPQFpqTZ9M8VOjpkuwFQWlT2Uo7Q6EoUi+Es4wSUpzXy7nFzdNqgztzYXIN4aq7mRe/qX0hbiX7is/AHd5CmtYEOEUpS+x0bNYf+OzRIBc8M28ty01CkG1xLn5Zp2BFzO94rfk0jYa5tPtf8Z3bX9pWzQNQJx9x5pX4TDx6RGS59asqsmB6Rh+BoLZBCoh4tLG1hj7ra3qRLb4pTZqcD1rn7cv3lkf1BMEetjl5PKNXQJ3q31vl8mcoojJeupvtFEBKKZBuXc/VgI48C+dGO34ckE7XlaEivdWXCY77FiQ5JWGxaHJ0+xh18/O7hFS0d8/tikNed+OKNH+XdNFoj2IQPiNXAaM/B3rzvJ8K4o5ArYaVr9HIaOacIPIB4lcnEI2/13JmDCJ+Z5GLce14g9vIjY/Spdg8bqvY9mOR6QtAQjh/0wQcoy1oyK44RzaeDePKGLuy8comitTlWn61G8PY2l2LIgCIQDkKI/lHDBVb5s+p9kXi9Qq0AXZ1um2XTRbOoAL8Ix+5iMm5pv3gAcgUitn6BcIno12RCqkj8pV+Aq5EFQ3n4DNlePzwCjRTFPenpEALnTL8pztGIqe8Tx27xVJ9MDHw1Bwf07Ul/7seIpbQR1pibgIuv+yls7+wmQ7mfPxyC3Lm2GyPv4wsiZtXIZaWehqXhW9MQcQsjsRQwZ49p6xufEb7nYhdCQZeSAELVRc2Ae15ov/v++Eqs1b/wkJpHoKtXldTR5CbxPIMTQg99vjQ6oEzcwKT/DNy7QQcyWJrdLvnDRYgQ0I1TNoOfF43Pm8N+UFUgYKxkYTVCeKzEjH6TF8E+Tjw==
  template:
    metadata:
      name: s3-worker-secrets
      namespace: s3-worker
    type: Opaque
