---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pull
  namespace: clickhouse-worker
spec:
  encryptedData:
    .dockerconfigjson: AgAVpk9OKizJbxJ68tWY+kO3JwLFsEVDw85P5E9nh5/poP2rcDtEFGLDWb72C/bYxPKafsZzDdS2Bn4aiYlEPuk8K4+Olkzzl0mKButeNcEorU1eQyxX/J068h8klmph4HYsE0B7BNgHq6FRhpeelP5ix94z6tZOhiwRB9TP08JNRfGuB0pdTlkaNE5hNIzpev81EDe5F8Buv4LPMrfCSFFSkuNs+ZoUd9IRPbRBVcRS1047xac+IjSmug55O2BgxjQvUlWxe4ZLCkWoYAa9B59qCAYa8ftUEBMkFwkxOrFCsU/Kd5MaHQfN37RAjj0/7rCpMMG1t2dnwNd0gsD/wl6ika0HGVtTqCNcaadsWe9JbwI+AynyEFGUN7R4+95yWKGA0p7JJKRbyVRXsM0aIf+/cmLswgRyUVirwka0K5bh9zDbhx9+GcbNI507Mq6CZlCAbu/6DTqXHFAeTJxyLKsMipWcF4WAAWTD1L+VgcnVFjRSNQuXTCAUSq7hXbb5jCY1j03J6EIo3LJoHx0tkZleUpragTLROao7EuwC4kg2uSVeLqLaHvH+MPeveiUCZoRt5WrWWVmJ+KsNCIRMS1D0D79Z1HjpbXwOQnkiuM1IMGKjDoUFmhM0Q0ZrByAJs75o4dtADZ/BLC44arY/Qi3iMHDBiRkog8qT38XXv1tIFis7cnWtQeEcmht2K6puxNzTLfigRulGjMltU+5OxWjsSpUY0MTCCswMxJ6RIY7MIfmZPMETgJIMCdekhNSl917jgBwzuMBEN+9a9cBpPtr4mc4egceNRhXeHS9VwpgtpnDJtNWZ7mKvqBclZOKmLMrFL8XNDbSLJO90WqS1xJRx0TRz7HY98hCzvwD/Mw6z2WDf1KVxA4kf0y4Mi81x3py8OmTFbSArrFsXmIQYwv8WYG0w8l0LF1nswQNlGdf+gu+xHAo+//dB1IcdxZl58A==
  template:
    metadata:
      name: dockerhub-pull
      namespace: clickhouse-worker
    type: kubernetes.io/dockerconfigjson
